name: Azure App Service - aztf13-webapp, Build and deploy

on:
  push:
    branches: [ master ]         # change to 'main' if needed
    paths:
      - 'appServiceSlot/**'
  workflow_dispatch:

concurrency:
  group: deploy-aztf13
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore (solution)
        run: dotnet restore appServiceSlot/SlotDemo.sln

      - name: Build (solution)
        run: dotnet build appServiceSlot/SlotDemo.sln --configuration Release --no-restore

      - name: Publish (project)
        run: dotnet publish appServiceSlot/SlotDemo/SlotDemo.csproj --configuration Release --output appServiceSlot/publish --no-build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: aztf13-webapp
          package: appServiceSlot/publish
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6447B1ABDC7B44C898B01D65369B7F8D }}
